# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rental
    ports:
        - "3308:3306"
