# Use root/example as user/password credentials
version: '3.1'

services:
    db:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: rental
        ports:
            - "3306:3306"
        
    rabbitmq:
        build: .
        ports:
          - "127.0.0.1:4369:4369"
          - "5671:5671"
          - "5672:5672"
          - "127.0.0.1:15671:15671"
          - "127.0.0.1:15672:15672"
          - "127.0.0.1:25672:25672"
        volumes:
          - ./tls:/etc/rabbitmq/tls
        #environment:
          # The env vars below are defaults. You can just leave them out if you want
          #RABBITMQ_ERLANG_COOKIE:
          #RABBITMQ_DEFAULT_VHOST: /
          #RABBITMQ_DEFAULT_USER: guest
          #RABBITMQ_DEFAULT_PASS: guest
          #RABBITMQ_MQTT_VHOST: /
          #RABBITMQ_MQTT_EXCHANGE: amq.topic
          #RABBITMQ_MQTT_DEFAULT_USER: guest
          #RABBITMQ_MQTT_DEFAULT_PASS: guest        
